[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ignored_error_codes = [
    9302,
] # Ignore the return value warning from low level calls

# Formatter
[fmt]
multiline_func_header = "all" # Or  params_first
contract_new_lines = true
line_length = 120
#bracket_spacing = true
wrap_comments = true
sort_imports = true
number_underscore = "thousands"
ignore = ["./script/**/*", "./lib/**/*"] # Paths to ignore from formatting

# Linter
[lint]
#lint_on_build = false
exclude_lints = ["screaming-snake-case-immutable", "mixed-case-variable"]
ignore = ["./test/**/*"]

# Fuzzing configs
[fuzz]
runs = 512

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
